# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/EngagementOrganizer.SPA/*
    exclude:
    - pipelines/*

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd .\src\EngagementOrganizer.SPA\
      npm install
      npm run build -- --prod --base-href ./ --outputPath="$(Pipeline.Workspace)\dist\" --configuration='production'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\dist\'
    artifact: 'ENgagementOrganizer.SPA'
    publishLocation: 'pipeline'