name: Deploy Backend on Azure

on:
  workflow_dispatch:
   inputs:
     environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        type: environment

jobs:
  Deploy-Backend:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Download Backend Artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: build-backend.yml
          name: organizer-backend
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./deploy

      - name: Config Settings Substitution
        shell: bash
        run: |
          for file in appsettings.json appsettings.Development.json appsettings.Production.json; do
            jq --arg apikeys "$API_KEYS" --arg dbpath "$DB_PATH" '.ApiKeys = $apikeys | .DatabasePath = $dbpath' "deploy/$file" > "deploy/$file.tmp"
            mv "deploy/$file.tmp" "deploy/$file"
          done
        env:
          API_KEYS: ${{ secrets.APPSERVICE_CONFIG_APIKEY }}
          DB_PATH: ${{ vars.DATABASE_PATH }}

      - name: Deploy Backend
        uses: azure/webapps-deploy@v3
        with:
          app-name:    ${{ vars.APPSERVICENAME }}
          package: ./deploy
